### ISSUE TITLE
HydroShoot tutorial

### ISSUE THREAD

**Issue by pradal** [openalea/hydroshoot#10]
New tutorials are built on [openalea web site](https://openalea.rtfd.io).
Please give us a link to be able to build a tutorial.
Then @bbrument will be able to publish it on the website.

**Comment by RamiALBASHA** [comment]
@pradal could you please tell me where to find the jupyter tutorial?

**Comment by RamiALBASHA** [comment]
The tutorial is here
https://nbviewer.jupyter.org/github/openalea/openalea.rtfd.io/blob/master/example/hydroshoot_grapevine.ipynb
Thank you guys !

**Comment by pradal** [comment]
You can look at the OpenAlea gallery on [openalea website](https://openalea.rtfd.io)
Or directly at 
[tuto](https://nbviewer.jupyter.org/github/openalea/openalea.rtfd.io/blob/master/example/hydroshoot_grapevine.ipynb)
