### ISSUE TITLE
conda package uploading failed

### ISSUE THREAD

**Issue by RamiALBASHA** [openalea/hydroshoot#101]
@pradal @thomasarsouze , anyone has an idea ?

https://github.com/openalea/hydroshoot/actions/runs/4636910419/jobs/8205275534#step:4:3600

![image](https://user-images.githubusercontent.com/20944441/230585758-02ab4a91-99d6-40e1-ba01-daf4a34a191f.png)

**Comment by pradal** [comment]
Yes. Token has expired. We will look at it

**Comment by thomasarsouze** [comment]
Just changed it. It's ok for next 10 years

**Comment by RamiALBASHA** [comment]
good news! thanks 👍
