### ISSUE TITLE
Installing Hydroshoot on Windows - canestra has not finished properly => STOP

### ISSUE THREAD

**Issue by rarygit** [openalea/hydroshoot#13]
Installed hydroshoot (master) using "python setup.py install" in Windows 8 conda environment.
All other packages - visualea, mtg, plantgl, caribu etc - successfully installed.

Runs until PlantGL 3D View pops up, showing plant geometry (fig1a).
It seems that canestrad.exe is not happy (fig.1b) with linking to hydroshoot,
after the 'pirouette' stage.

Any suggestions with correctly installing hydroshoot on windows?
or solving the error output below?

Thanks
![fig1a_PlantGL 3D Viewer](https://user-images.githubusercontent.com/16574504/67151659-7a8e3880-f2c9-11e9-8cae-f4e669e366c5.jpg)
![fig1b_canestrad exe - Entry Point Not Found](https://user-images.githubusercontent.com/16574504/67151660-7feb8300-f2c9-11e9-8d43-6b08273d24d7.jpg)

>python sim.py

WARNING: QApplication was not created in the main() thread.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ Project:  C:\Users\office\Downloads\hydroshoot-master\example\modularity\ws\si
m_2/
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
GDD since budbreak = 928 ┬░Cd
Energy_budget: True
Hydraulic structure: True
Computing form factors...
... pirouette
>>>  canestra has not finished properly => STOP
Traceback (most recent call last):
  File "sim.py", line 40, in <module>
    model.run(g, str(getcwd()) + '/', scene)
  File "D:\Miniconda2\envs\oat1clone\lib\site-packages\hydroshoot-1.0.0-py2.7.eg
g\hydroshoot\model.py", line 170, in run
    unit_scene_length=unit_scene_length)
  File "D:\Miniconda2\envs\oat1clone\lib\site-packages\hydroshoot-1.0.0-py2.7.eg
g\hydroshoot\energy.py", line 121, in form_factors_simplified
    raw, aggregated = caribu_scene.run(direct=True, infinite=infinite, split_fac
e=False, simplify=True)
  File "d:\miniconda2\envs\oat1clone\lib\site-packages\alinea.caribu-1.4.4-py2.7
-win-amd64.egg\alinea\caribu\CaribuScene.py", line 537, in run
    screen_size=screen_size)
  File "d:\miniconda2\envs\oat1clone\lib\site-packages\alinea.caribu-1.4.4-py2.7
-win-amd64.egg\alinea\caribu\caribu.py", line 205, in raycasting
    algo.run()
  File "d:\miniconda2\envs\oat1clone\lib\site-packages\alinea.caribu-1.4.4-py2.7
-win-amd64.egg\alinea\caribu\caribu_shell.py", line 405, in run
    self.canestra(opt)
  File "d:\miniconda2\envs\oat1clone\lib\site-packages\alinea.caribu-1.4.4-py2.7
-win-amd64.egg\alinea\caribu\caribu_shell.py", line 539, in canestra
    raise CaribuRunError(''.join(msg))
alinea.caribu.caribu_shell.CaribuRunError

**Comment by rarygit** [comment]
Hydroshoot runs OK on Linux. This can be closed until windows version released.

**Comment by pradal** [comment]
Thanks @rarygit for this issue.
We have a problem to distribute Caribu on Windows, because it only compiles using MinGW and we do not know yet how to build it on Windows on conda using the mingw compiler.

**Comment by rarygit** [comment]
Thanks for replying Christophe! For now I am running hydroshoot on Ubuntu, so far so good.  21.10.2019, 09:18, "Christophe Pradal" <notifications@github.com>:Thanks @rarygit for this issue.
We have a problem to distribute Caribu on Windows, because it only compiles using MinGW and we do not know yet how to build it on Windows on conda using the mingw compiler.
