### ISSUE TITLE
python version conflicts while installing hydroshoot

### ISSUE THREAD

**Issue by junqi108** [openalea/hydroshoot#15]
Hi Rami, Christian, and Christophe: 
I am trying to install openAlea and hydroshoot on my linux system Ubuntu 18.04. however, i met lots of version problems. 
Initially, the system has Python 3.7, 3.6 preinstalled. I installed python 2.7 and use environmenal variables to set it as the default version. 
I have tried to install the hydroshoot python package using the conda environment, as given in this link: https://openalea.readthedocs.io/en/latest/install.html

However, there were conflicts in the python packages, as seen in the snapshot below. We have similar conflicts while installing other packages such as mtg too.
It would really help if we have a comprehensive guide on the version that is needed along with a step by step instruction on installation on openlea, hydroshoot and other dependent packages.
![Error](https://user-images.githubusercontent.com/13222562/69775581-05821d00-11fe-11ea-8e0f-d858b8072bf8.png)
thanks very much in advance. 
yours Junqi Zhu

**Comment by RamiALBASHA** [comment]
Hi Junqi,
Thank you for your feedback.
I am having also alot of incompatibility troubles since I moved to ubuntu 18.04. I'll try to make a fix that out with @christian34 and @pradal and make a tuto for installation asap.
Kind regards
Rami
P.S. If you have an ubuntu 16.04 somewhere (as under windows 10) try to install hydroshoot on it, that should works

**Comment by junqi108** [comment]
hi Rami: 
thanks for the quick reply. I will try ubuntu 16.04 in the VM then. 
cheers.
junqi

**Comment by junqi108** [comment]
Hi Rami: 
we still got the version conflicts issues in ubuntu 16.04. the openAlea was installed correctly, but when we use conda to install hydroShoot, we met some problems. 
These are the steps followed for Hydroshoot installation:
1.	Installed VM with Linux 16.04 OS and this came with Python 2.7.12
2.	Installed conda: Miniconda2 Linux 64-bit for Python 2.7 (this installs some python packages such as openssl with specific version)
3.	Created Conda Environment and installed openalea packages.
4.	Activated the Conda Environment
5.	Installed Hydroshoot using Conda in this environment – this step fails causing resulting in conflict in the python packages.  

Certain packages such as SQLite3, OpenSSL, etc are getting installed together with Miniconda2, and when Hydroshoot is installed in Step 6, these packages are causing issues due to conflict in the earlier version installed through Miniconda2.

can i ask which conda version do you use to install the hydroshoot package? and how do you normally solve this issues. we feel the version of conda installed is the main cause of conflicts occurring in python package?
junqi

**Comment by pradal** [comment]
Dear Junqi,

We are working currently on the installation of the package. We will
update the info about installation next week.
Stay tuned.
Cheers
Christophe

Le 29/11/2019 à 04:53, Junqi ZHU a écrit :

**Comment by RamiALBASHA** [comment]
@junqi108 
> can i ask which conda version do you use to install the hydroshoot package? and how do you normally solve this issues. we feel the version of conda installed is the main cause of conflicts occurring in python package?

I never used conda to install HydroShoot. I used to clone hydroshoot and install it locally as `develop` :
go to the project repository and execute 
```bash
python setup.py develop
```
You may though face some troubles, here's some useful solutions I found when installed the last time hydroshoot under ubuntu VM [hs_installation.txt](https://github.com/openalea/hydroshoot/files/3904306/hs_installation.txt)

Let me know if you get it works !

Kind regards,
Rami

**Comment by junqi108** [comment]
> Dear Junqi, We are working currently on the installation of the package. We will update the info about installation next week. Stay tuned. Cheers Christophe Le 29/11/2019 à 04:53, Junqi ZHU a écrit :
> […](#)

Thanks Christophe. I will wait for your news. Junqi

**Comment by junqi108** [comment]
> @junqi108
> 
> > can i ask which conda version do you use to install the hydroshoot package? and how do you normally solve this issues. we feel the version of conda installed is the main cause of conflicts occurring in python package?
> 
> I never used conda to install HydroShoot. I used to clone hydroshoot and install it locally as `develop` :
> go to the project repository and execute
> 
> ```shell
> python setup.py develop
> ```
> 
> You may though face some troubles, here's some useful solutions I found when installed the last time hydroshoot under ubuntu VM [hs_installation.txt](https://github.com/openalea/hydroshoot/files/3904306/hs_installation.txt)
> 
> Let me know if you get it works !
> 
> Kind regards,
> Rami

Thanks Rami. Do you install openAlea through conda first or not? I am just wondering is openAlea need to installed first before you run setup.py develop?
Cheers junqi

**Comment by junqi108** [comment]
Hi @RamiALBASHA and @pradal:
Thanks for the tips. I used the python setup.py develop command after installing the openAlea through conda, and then installed the missing library individually, and it works now, cheers^-^.
one problem i met now is the scene frozen after running the code: 
scene = display.visu(g, def_elmnt_color_dict=True, scene=Scene(),
                     view_result=True) 
by the way, Rami, could you give a little bit explanation of the meaning of the head of the digit input file: 
Souche;tronc;element;sarment;rameau;rang;X;Y;Z;Diam
1;0;1;0;0;0;-2.54;0.68;2.45;7
1;0;2;0;0;0;-1.17;3.1;8.58;5.418
trunk (main trunk of a vine); branch (canes or cordons), twig (annual shoots? ); rank; X; Y; Z (coordinates); Diam (diameter of the shoot or the leaves?) is the leaf size information included in this data as well? 
could we communicate this by email? my email address is junqi.zhu@plantandfood.co.nz

**Comment by RamiALBASHA** [comment]
@junqi108 
> and it works now, cheers^-^

That's good news !
> one problem i met now is the scene frozen after running the code

You should be expecting the scene to freeze whilst the code is still running. Does it still freeze after the simulation is finisehd?
Otherwise, the headers given in the digit files are quite unformal names given at the time by Eric and myself at the LEPSE :

- souche: vine
- tronc: not only trunk but this includes all shoots older than 2 years old
- element: phytomer or pyhtomer-like element (any objet that delimits visually the digitized axis)
- sarment: lignified shoot from the laster year
- rameau: current-year shoot
- rang: rank or order of your element starting from the base to apex
- X;Y;Z: coordinates of the head of each element
- Diam: diameter of the digitized element

**This nomenclature has no strict botanical meaning and should not be taken for such. I'll will remove, among others, the `architecture.py` module in the future so that HydoShoot will only include `exchange.py`, `energy.py` and `hydraulic.py`.**

**Comment by pradal** [comment]
@junqi108: Freeze
If you run the code interactively, you need on Linux to activate a qt mode:
%gui qt4
Then, another thread for the graphics is launched and the 3D viewer will not freeze anymore

**Comment by junqi108** [comment]
> @junqi108: Freeze
> If you run the code interactively, you need on Linux to activate a qt mode:
> %gui qt4
> Then, another thread for the graphics is launched and the 3D viewer will not freeze anymore

thanks Pradal. It works well now. cheers. junqi
