### ISSUE TITLE
PlantGL crash _ Qt5 interactive GUI problem

### ISSUE THREAD

**Issue by jazzsta** [openalea/hydroshoot#43]
@RamiALBASHA 
I got the follwing error:  when executing the example, the graphik window was crashing instantly after opening and the program was being blocked that point.

We found [this ](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360008558320-Enable-IPython-gui-with-qt5-in-Pycharm )relative discussion, and so we managed to solve the issue by running the command `%gui qt5` before executing display.visu(....)

Is there a more general solution ?

**Comment by RamiALBASHA** [comment]
Thank you @jazzsta for your feedback.
This is probably due to your IDE configuration. I'll lookup for a solution asap.

**Comment by pradal** [comment]
Same issue openalea/plantgl#2
You just need in jupyter or ipython use the command  at the begining

    %gui qt

**Comment by RamiALBASHA** [comment]
Thanks @pradal, I saw that one.
The problem here is happening using the python interpreter in PyCharm. I think that we may find another permanent solution to avoid typing `%gui qt5` at each execution.

**Comment by pradal** [comment]
PyCharm say that they are incompatible with qt loop. 
To avoid typing %gui qt you may also declaring environment variable : that's what I have done in visualea

Otherelse you may also define an ipython configuration: 
InteractiveShellApp.gui='qt5'
