### ISSUE TITLE
Warnings and methods deprecated

### ISSUE THREAD

**Issue by pradal** [openalea/hydroshoot#52]
There are several warnings: 
DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
    azi = -scipy.arccos(min(max(-1,x/scipy.sqrt(x**2+y**2)),1))

- scipy.arccos, arcsin, radians, sqrt, ...
- scipy.array

Also
 The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.

**Comment by RamiALBASHA** [comment]
I have seen all the modifications related to this issue. Thank you @pradal 
Were you able to run de the code in order to ensure that the simulation result remains the same ?

**Comment by pradal** [comment]
I have run all the tests. Is it enough?
I will add the tests to the CI

**Comment by RamiALBASHA** [comment]
The tests are enough, thanks Christophe.
I have just updated the tests to follow last bugfixes in the diffuse irradiance calculations. All branches are up to date.

**Comment by pradal** [comment]
Excellent.
I will update the conda meta.yaml to run the tests.
Then, all PR will be tested, and package will be uploaded when the test pass
