### ISSUE TITLE
conda install does not include the latest version

### ISSUE THREAD

**Issue by RamiALBASHA** [openalea/hydroshoot#69]
conda does not seem to include the modifications perfomed recently (at least after Sept 14th).
To verify, install hyrdoshoot following the procedure from README, then compare line 1139 in architecture with that in 'master'. Without the modifications indluded in hydroshoot, the model raises an error.
https://github.com/openalea/hydroshoot/blob/c57eb5ccf9ca4c9f3fe4a067e2818f4ad9baaf07/src/hydroshoot/architecture.py#L1139

any idea @pradal ? Thanks in advance !

**Comment by pradal** [comment]
Done.
Can you test the ew version, then close the issue please?
And before, can you add a test that fails if the package is not fixed?
