### ISSUE TITLE
remove g from hydroshoot inputs class

### ISSUE THREAD

**Issue by RamiALBASHA** [openalea/hydroshoot#76]
it is misleading to include hydroshoot object as an input to its own input...
https://github.com/openalea/hydroshoot/blob/3eae391043b45838236d28e8f671d80112227168/src/hydroshoot/io.py#L16

**Comment by pradal** [comment]
It may be interesting to discuss this.
For compatibility with other OpenAlea model, this is quite mandatory.
If we modify this pattern, this has to be changed elsewhere.
So happy to have this "formal" discussion
